### ISSUE TITLE
ERROR: fatal: could not read Username for 'https://github.com': during installation

### ISSUE THREAD

**Issue by daniphilia** [wealdtech/ethereal#1]
Output:

cd .; git clone https://github.com/wealdtech/go-domainsale /home/dani/go/src/github.com
/wealdtech/go-domainsale
Cloning into '/home/dani/go/src/github.com/wealdtech/go-domainsale'...
fatal: could not read Username for 'https://github.com': terminal prompts disabled
package github.com/wealdtech/go-domainsale/domainsalecontract: exit status 128

**Comment by mcdee** [comment]
Sorry that was old code; I've removed it so you should be okay now.  Please let me know if you have further problems installing Ethereal.
