### ISSUE TITLE
Failed to obtain chain ID: Post https://api.orinocopay.com:8546/: x509: certificate has expired or is not yet valid

### ISSUE THREAD

**Issue by Fyde1** [wealdtech/ethereal#10]
Ethereal doesn't work for me anymore, it seems like the SSL certificate is expired.

**Comment by mcdee** [comment]
Apologies for this, the certificate renewed by the daemon did not pick it up.  I've restarted the daemon so it should work now; please let me know if not.

I've updated the certificate renewal script so it should pick up renewals automatically in future.

Thank you for reporting this issue.

**Comment by Fyde1** [comment]
I'm getting this error again since about 3 days ago.

**Comment by mcdee** [comment]
Renew script was misbehaving; should be fixed again now.

Mid-term (in the next month or so) I'm moving the default endpoints to infura so this should no longer be an issue.
