### ISSUE TITLE
Build fails on current release / latest golang

### ISSUE THREAD

**Issue by PixyMisa** [wealdtech/ethereal#13]
ens@sjc-dev1:~$ go get github.com/wealdtech/ethereal
# github.com/wealdtech/ethereal/util/txdata
go/src/github.com/wealdtech/ethereal/util/txdata/signature.go:56:24: not enough arguments in call to abi.NewType
	have (string, nil)
	want (string, string, []abi.ArgumentMarshaling)
go/src/github.com/wealdtech/ethereal/util/txdata/signature.go:89:24: not enough arguments in call to abi.NewType
	have (string, nil)
	want (string, string, []abi.ArgumentMarshaling)
	
	
ens@sjc-dev1:~$ go version
go version go1.13.4 linux/amd64

Following the instructions in  #11 I was able to clone the V2 branch and build that without error.

**Comment by mcdee** [comment]
Thank you for reporting this issue.  It comes from go-ethereum's deep and abiding inability to follow semver.  I have pushed an update for this, so a `go get -u github.com/wealdtech/ethereal` should fix this.  If not please let me know.
