### ISSUE TITLE
Build failing on current release

### ISSUE THREAD

**Issue by Forky-the-forking** [wealdtech/ethereal#14]
this is the error after the : "go get -u github.com/wealdtech/ethereal"

go: finding module for package github.com/prometheus/prometheus/util/flock
go: gopkg.in/yaml.v2 upgrade => v2.2.8
go: github.com/spf13/jwalterweatherman upgrade => v1.1.0
go: golang.org/x/net upgrade => v0.0.0-20200320220750-118fecf932d8
go: golang.org/x/crypto upgrade => v0.0.0-20200320181102-891825fb96df
go: golang.org/x/sys upgrade => v0.0.0-20200321134203-328b4cd54aae
go: github.com/konsorten/go-windows-terminal-sequences upgrade => v1.0.2
go: github.com/golang/protobuf upgrade => v1.3.5
go: github.com/spf13/pflag upgrade => v1.0.5
go: golang.org/x/text upgrade => v0.3.2
go: github.com/fsnotify/fsnotify upgrade => v1.4.9
go: github.com/mitchellh/mapstructure upgrade => v1.2.2
go: gopkg.in/ini.v1 upgrade => v1.55.0
go: github.com/ethereum/go-ethereum upgrade => v1.9.12
go: github.com/pelletier/go-toml upgrade => v1.6.0
go: github.com/google/uuid upgrade => v1.1.1
go: github.com/spf13/afero upgrade => v1.2.2
go: github.com/golang/snappy upgrade => v0.0.1
go: github.com/sirupsen/logrus upgrade => v1.4.2
go: github.com/karalabe/hid upgrade => v1.0.0
go: github.com/wealdtech/go-string2eth upgrade => v1.1.0
go: github.com/mattn/go-colorable upgrade => v0.1.6
go: github.com/jackpal/go-nat-pmp upgrade => v1.0.2
go: github.com/spf13/cast upgrade => v1.3.1
go: github.com/minio/sha256-simd upgrade => v0.1.1
go: github.com/btcsuite/btcd upgrade => v0.20.1-beta
go: github.com/allegro/bigcache upgrade => v1.2.1
go: github.com/rs/cors upgrade => v1.7.0
go: github.com/spf13/viper upgrade => v1.6.2
go: github.com/fjl/memsize upgrade => v0.0.0-20190710130421-bcb5799ab5e5
go: github.com/spaolacci/murmur3 upgrade => v1.1.0
go: github.com/aristanetworks/goarista upgrade => v0.0.0-20200310212843-2da4c1f5881b
go: github.com/magiconair/properties upgrade => v1.8.1
go: github.com/multiformats/go-multihash upgrade => v0.0.13
go: github.com/mr-tron/base58 upgrade => v1.1.3
go: github.com/mattn/go-isatty upgrade => v0.0.12
go: finding module for package github.com/prometheus/prometheus/util/flock
..\go\pkg\mod\github.com\ethereum\go-ethereum@v1.8.20\node\node.go:36:2: module github.com/prometheus/prometheus@latest found (v2.5.0+incompatible), but does not contain package github.com/prometheus/prometheus/util/flock

**Comment by mcdee** [comment]
`-u` will attempt to upgrade the dependencies, which could cause problems.  Could you remove the package and try again with just `go get github.com/wealdtech/ethereal`?

**Comment by mcdee** [comment]
Closed due to inactivity; documentation has been updated in the meantime to use GO111MODULE and @latest rather than `-u`
