### ISSUE TITLE
ethereal: command not found

### ISSUE THREAD

**Issue by missingbeacon** [wealdtech/ethereal#15]
Hi

im using ubuntu 16.04, updated etc. cant seem to get this working

abe@abe:~/go$ go get "github.com/wealdtech/ethereal"
package context: unrecognized import path "context" (import path does not begin with hostname)
package math/bits: unrecognized import path "math/bits" (import path does not begin with hostname)
package github.com/cespare/xxhash/v2: cannot find package "github.com/cespare/xxhash/v2" in any of:
        /usr/lib/go-1.6/src/github.com/cespare/xxhash/v2 (from $GOROOT)
        /home/abe/go/src/github.com/cespare/xxhash/v2 (from $GOPATH)
package net/http/httptrace: unrecognized import path "net/http/httptrace" (import path does not begin with hostname)
package github.com/wealdtech/go-ens/v3: cannot find package "github.com/wealdtech/go-ens/v3" in any of:
        /usr/lib/go-1.6/src/github.com/wealdtech/go-ens/v3 (from $GOROOT)
        /home/abe/go/src/github.com/wealdtech/go-ens/v3 (from $GOPATH)
abe@abe:~/go$ ethereal
ethereal: command not found
abe@abe:~/go$

**Comment by mcdee** [comment]
Thank you for reporting this issue.  You need to run at least version 1.13 of go to build ethereal.  I've updated the documentation to make this explicit.
