### ISSUE TITLE
"command not found" on Ubuntu 20.4 LTS

### ISSUE THREAD

**Issue by DaniellMesquita** [wealdtech/ethereal#23]
@mcdee

go version go1.13.8 linux/amd64

Installed go through `sudo apt install golang-go`

Installed ethereal through `GO111MODULE=on go get github.com/wealdtech/ethereal@latest` and also tried both `go get -u -v github.com/wealdtech/ethereal` and `GO111MODULE=on go get -u -v github.com/wealdtech/ethereal`.

What is the workaround for an working `ethereal` cmd?

**Comment by DaniellMesquita** [comment]
If any interest, I was able to compile it for Linux x64, and it is working like a charm on /usr/bin:
[Uploading ethereal_v2.3.25_linux-amd64.tar.gz…]()

I kindly ask the developers if they need someone to help distributing these binaries, because: letting users to build themselves ethereal is counter-intuitive. Users should be able to simply download and chmod the binaries like they do with ipfs/ipget. Even an .sh script to run an one-line on terminal to download the binaries and install for user.

**Comment by DaniellMesquita** [comment]
Even without help, I would implement the update system on https://github.com/Floflis anyway, by querying the centralized .eth.link for the IPFS CID directly instead of using ethereal. But thankfully I was able to compile it and install.

There is an fork (not here to implement new things nor replace ethereal) where I'm, updating with the ready binaries: https://github.com/Floflis/ethereal/releases/tag/v2.3.25
I'll update this fork to also offer an one-line install script for ethereal, without requiring technical skills from its users.

**Comment by DaniellMesquita** [comment]
I'll study how to cross-compile an go project, so there will be other binaries available.
So, the one-line .sh script could automatically detect the arch/platform before choosing the proper binary.

**Comment by mcdee** [comment]
Pre-built binaries are now available in the releases section, and a docker image is also available.
