### ISSUE TITLE
Infura error

### ISSUE THREAD

**Issue by DaniellMesquita** [wealdtech/ethereal#25]
> Failed to connect to Ethereum node: Post "https://mainnet.infura.io/v3/831a5442dc2e4536a9f8dee4ea1707a6": dial tcp: lookup mainnet.infura.io: no such host

![Screenshot from 2021-05-10 11-41-23](https://user-images.githubusercontent.com/6765277/117677285-b4ad7c80-b184-11eb-8033-944504e5c1c1.png)
![Screenshot from 2021-05-10 11-41-27](https://user-images.githubusercontent.com/6765277/117677373-c55df280-b184-11eb-8aee-00b7336233c3.png)

**Comment by mcdee** [comment]
That looks to be a network/resolution error on the host side.  mainnet.infura.io appears to be present and operating fine.

**Comment by DaniellMesquita** [comment]
@mcdee, this error isn't only in my side:
https://archive.is/Er3sv
https://archive.is/FuItc

**Comment by DaniellMesquita** [comment]
@mcdee, then what you suggest to fix this?

**Comment by mcdee** [comment]
Given this looks like a transient network issue, it should fix itself.

**Comment by DaniellMesquita** [comment]
Ok, now it worked:

![Screenshot from 2021-05-10 14-30-37](https://user-images.githubusercontent.com/6765277/117700656-ad926880-b19c-11eb-9a9e-bbe8d8d566cd.png)

But how to avoid these issues happening again? Such as using an fallback Ethereum node?

**Comment by DaniellMesquita** [comment]
Happened again:
![Screenshot from 2021-05-10 15-18-46](https://user-images.githubusercontent.com/6765277/117705964-1a106600-b1a3-11eb-987f-3dcd3e51ed18.png)

This wasn't happening before, as Web3Updater used ethereal and its Infura node with reliable stability.

**Comment by mcdee** [comment]
If the infura node is proving unreliable a local geth node can be used instead, or a different service provider.  The alternative provider can be specified with the `--connection` parameter.
