### ISSUE TITLE
Install Fails -- no error

### ISSUE THREAD

**Issue by darrenalcorn** [wealdtech/ethereal#3]
I was able to install Go but when I run go get -u github.com/wealdtech/ethereal, I do not see any errors and afterwards “ethereal” command is not found. I also ran updatedb && locate ethereal and don’t find anything.

**Comment by mcdee** [comment]
Go has its own directory system, based around GOPATH.  Please see https://github.com/golang/go/wiki/SettingGOPATH for details on how to set your GOPATH.

You should find the Ethereal binary in the $GOPATH/bin directory, for example (this is on Unix but the above link provides GOPATH information for Windows as well):

    $ export GOPATH=/home/jgm/example
    $ ls /home/jgm/example/bin
    ls: cannot access '/home/jgm/example/bin': No such file or directory
    $ go get -u github.com/wealdtech/ethereal
    $ ls /home/jgm/example/bin
    ethereal
    $

Please let me know if this helps to explain where Ethereal is located, and if you need further assistance.

**Comment by jaslo** [comment]
I have GOPATH set and I still get a couple of package install errors:

# github.com/wealdtech/ethereal/ens
go/src/github.com/wealdtech/ethereal/ens/registrar.go:186:32: cannot use big.NewInt(200000) (type *big.Int) as type uint64 in assignment
# github.com/orinocopay/go-etherutils/ens
go/src/github.com/orinocopay/go-etherutils/ens/registrar.go:194:32: cannot use big.NewInt(200000) (type *big.Int) as type uint64 in assignment
➜  ~ go version
go version go1.9.2 darwin/amd64

**Comment by mcdee** [comment]
@jaslo a dependency changed, which caused this issue.  I've locked in the  dependencies so you should be able to do a `go get -u github.com/wealdtech/ethereal` now and it should compile.  If it continues to fail please open a new issue; thanks.

**Comment by jaslo** [comment]
works now! Thank you.

**Comment by n-drw** [comment]
`$ go get github.com/wealdtech/ethereal
# github.com/wealdtech/ethereal/vendor/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify
go/src/github.com/wealdtech/ethereal/vendor/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:51: cannot use refZero (type int) as type *_Ctype_struct___CFAllocator in argument to func literal
go/src/github.com/wealdtech/ethereal/vendor/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:165: cannot use refZero (type int) as type *_Ctype_struct___CFAllocator in argument to func literal
go/src/github.com/wealdtech/ethereal/vendor/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:166: cannot use refZero (type int) as type *_Ctype_struct___CFAllocator in argument to func literal`

This is what I'm getting with:
`$ go version
go version go1.10 darwin/amd64`

**Comment by mcdee** [comment]
@n-drw I altered the vendoring method; please try again with `go get -u github.com/wealdtech/ethereal` and see if it now works.
