### ISSUE TITLE
How to connect to other EVM sidechains (Polygon, XDai)

### ISSUE THREAD

**Issue by DaniellMesquita** [wealdtech/ethereal#33]
I've read README.md but only found about adding a single IPC network (and not a RPC with network ID like in MetaMask).

@mcdee How to connect to these networks via RPC directly using a command flag?

Polygon:
RPC: `https://rpc-mainnet.maticvigil.com/`
ID: `137`

XDai:
RPC: `https://rpc.xdaichain.com/`
ID: `100`

**Comment by mcdee** [comment]
ethereal is not designed to work with sidechains, however if they are fully rpc-compatible then most features will work albeit with oddities (e.g. ethereal assumes Ether is the base currency) and, as you mention, the network ID will be incorrect so that may also cause issues.

https://github.com/wealdtech/ethereal#access-to-ethereum-networks describes how to use other chains, e.g. `ethereal --connection=https://rpc.xdaichain.com/ ...`

**Comment by danimesq** [comment]
@mcdee 
Will there be an update to use a flag for a different denomination, such as XDAI and MATIC?

And how to use better gas estimatives for networks such as Polygon?
The following command:

`ethereal --connection="https://polygon-mainnet.public.blastapi.io" transaction send --from=$USER_ADDRESS --to=$destination_address --amount="0" --data "$plain_contents" --gaslimit 0 --wait`

Is stuck for countless minutes.
Once a time I was able to broadcast a transaction to Polygon PoS, which isn't happening anymore (and that time it was stuck too, but was at least accessible on polygonscan).

**Comment by danimesq** [comment]
Probably for other networks, it is estimating the gas that would be used for a simple "ETH" transfer, and not the IDM data included with it.

**Comment by danimesq** [comment]
Update (still not working, but at least now it did a response):

> ❯ bash blockchain-poster.sh test.txt 0x117483E977B4EdEe761486F645bca5824b02b1d3
> [DEBUG] plain_contents: 0x546573740A506F73742076696120434C4920696E7374656164206F662062726F777365720A416E6F746865722074657374206C696E650A4D6573736167650A
> Waiting for your transaction to be mined...
> Failed to send transaction: failed to send transaction: replacement transaction underpriced

**Comment by danimesq** [comment]
By changing the command to `ethereal --connection="https://polygon-mainnet.public.blastapi.io" --chainid=137 transaction send --from=$USER_ADDRESS --to=$destination_address --amount="0" --data "$plain_contents" --gaslimit 200 --debug --wait` (has added `--gaslimit 200`), at least now it tells an estimate:

> blockchain-writer-suite/poster/blockchain-poster on  main 
> ❯ bash blockchain-poster.sh test.txt 0x117483E977B4EdEe761486F645bca5824b02b1d3
> [DEBUG] plain_contents: 0x546573740A506F73742076696120434C4920696E7374656164206F662062726F777365720A416E6F746865722074657374206C696E650A4D6573736167650A
> Waiting for your transaction to be mined...
> Failed to send transaction: failed to send transaction: intrinsic gas too low: needed 22008, allowed 200

**Comment by danimesq** [comment]
**Update**: NOW IT WORKED!

The "trick" was adding `--priority-fee-per-gas "40 Gwei"`!

So, the idea in this case is to use a free gas meter API and get that value from it.
