### ISSUE TITLE
Unable to connect to ethereum node

### ISSUE THREAD

**Issue by nivshitrit** [wealdtech/ethereal#39]
been trying to get ethereal to run in a container inside kubernetes. not really sure what im doing wrong, trying to get basic connection with the public node and also with my private node and both are producing the following message:

Failed to connect to Ethereum node: unable to contact client

the command i was trying :
ethereal account list --network=goerli

also tried with my private node:
ethereal account list --connection=rpc-ip:8551

**Comment by mcdee** [comment]
This appears to be an issue with your kubernetes configuration, you need to ensure that ethereal has access to remote instances for this to work.
