### ISSUE TITLE
[Feature] Support for Starknet

### ISSUE THREAD

**Issue by danimesq** [wealdtech/ethereal#45]
Hard to believe this will be a thing, as it seems Starknet use different addresses and not using EVM.

**Comment by danimesq** [comment]
So here's a question: are there something like Ethereal for Starknet, so I can read/call/write Cairo contracts via CLI?

**Comment by mcdee** [comment]
`ethereal` is only for Ethereum.  It may work for some other EVM-compatible chains, but is neither tested on or support on these chains.  Outside of that it would by necessity require a completely different tool.

**Comment by danimesq** [comment]
**For anyone else looking for the same: I'VE FOUND AN "ETHEREAL" FOR STARKNET**:
- https://github.com/kariy/starknet-probe
